Refactored components to be in folders, added Characteristics feature, CSS tweaks
GreenHillUI/productApp pull request #67
Opened 2022-07-21 21:15 UTC by CotyJ

2022-07-21 21:42 UTC, BlandSchwad approved these changes
I appreciate the use of an index file for your component. Very classy.

2022-07-21 21:43 UTC, Dalphus requested changes
This pull request is way too large.
Please separate your tests into their own pull request
If you change the file structure of your code, make that its own PR as well
Also remove commented code in your final commit

esp. for larger pull requests, it is beneficial to leave comments yourself on github explaining what changes were made and why they were made

2022-07-22 00:21 UTC, Dalphus requested changes
don't use inline styling >:(

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/Review.jsx
> +          <div style={{ fontWeight: 'bold' }}>{firstLine}</div>
this should not be an inline style
use the `<b>` tag instead of div

2022-07-22 00:21 UTC, Dalphus commented on client/dist/styles/ratingsAndReviews.css
>  }
use the selector `#ratings-reviews b` here instead

2022-07-22 00:21 UTC, Dalphus commented on client/dist/styles/ratingsAndReviews.css
> +}
use `#ratings-reviews .stars` to style stars

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/Characteristics.jsx
> +// INCOMPLETE
remove this comment

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/Characteristics.jsx
> +  };
do not use inline styling

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/Characteristics.jsx
> +          <div style={{ display: 'inline', float: 'right' }}>Runs Loose</div>
:(

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/Characteristics.jsx
> +          <VscTriangleDown style={{ position: 'relative', left: getArrowPosition(resultsMeta.Width.value) }} />
`position: relative` should not be an inline style

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/Characteristics.jsx
> +          <div style={{ display: 'inline', float: 'right' }}>Runs Long</div>
styling

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/ReviewsList.jsx
>      console.log(event.target.value);
remove console.logs in your final commit

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/ReviewsList.jsx
> +  }
this function should be removed

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/ReviewsList.jsx
> +        onClick={() => addReviewModal()}
`onClick={() => addReviewModal()}`
can be
`onClick={addReviewModal}`

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/index.jsx
> +/**
lost semantic value when renaming this file
instead have default export in index.js that exports Ratings.jsx

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/index.jsx
> +function addStarAndBar(results, stars) {
this might be better suited as a component

2022-07-22 00:21 UTC, Dalphus commented on client/src/components/Ratings/index.jsx
> +}
this function should be removed

2022-07-22 00:21 UTC, Dalphus commented on spec/RR.test.js
> +/* eslint-disable no-undef */
should be in its own PR

2022-07-22 19:15 UTC, Dalphus approved these changes

2022-07-22 19:15 UTC, merged